# Build
FROM golang:alpine AS build

WORKDIR /app

COPY src/go.mod ./
COPY src/go.sum ./
RUN go mod download

COPY src/*.go ./

RUN go build -o /service


## Deploy
FROM alpine

WORKDIR /

COPY --from=build /service /service

EXPOSE 5000

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser:appgroup

ENTRYPOINT ["/service"]