version: "3.4"
services:
  about:
    build:
      context: ./about
    ports: 
      - "5000:5000"
    expose:
      - "5000"
  quote:
    build:
      context: ./quote
    ports: 
      - "5001:5000"
    expose:
      - "5000"
